### ISSUE TITLE
[Jekyll] Ruby Sass has reached end-of-life and should no longer be used

### ISSUE THREAD

**Issue by JarekParal** [RoboticsBrno/roboruka.robotickytabor.cz#44]
```
Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841 [this link doesn't work]
```

Considere upgrade to [sassc gem](https://github.com/sass/sassc-ruby#readme)

**Comment by JarekParal** [comment]
Probably the best solution is upgrade to [Jekyll 4.x](https://github.com/jekyll/jekyll-sass-converter/issues/74#issuecomment-516217160)

**Comment by JarekParal** [comment]
Unfortunately, after upgrade to Jekyll 4.x, there is problem with [`jekyll-minimagic`](https://github.com/zroger/jekyll-minimagick) plugin:
https://stackoverflow.com/questions/58438386/jekyll-4-0-build-fails-with-nomethoderror

**Comment by JarekParal** [comment]
I tried to update Jekyll to 4.x and replace `jekyll-minimagic` with [`jekyll-responsive-image`](https://github.com/wildlyinaccurate/jekyll-responsive-image). But I got to the state with this error:

```
bundle exec jekyll serve --trace
Configuration file: /mnt/c/Users/JPA/Documents/JPA-Documents/_Track/roboruka.robotickytabor.cz/_config.yml
            Source: /mnt/c/Users/JPA/Documents/JPA-Documents/_Track/roboruka.robotickytabor.cz
       Destination: /mnt/c/Users/JPA/Documents/JPA-Documents/_Track/roboruka.robotickytabor.cz/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: undefined method `start_with?' for nil:NilClass in /mnt/c/Users/JPA/Documents/JPA-Documents/_Track/roboruka.robotickytabor.cz/_guides/002 - Obecné rady.md
Traceback (most recent call last):
        68: from /home/jpa/gems/bin/jekyll:23:in `<main>'
        67: from /home/jpa/gems/bin/jekyll:23:in `load'
        66: from /home/jpa/gems/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
        65: from /home/jpa/gems/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        64: from /home/jpa/gems/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        63: from /home/jpa/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        62: from /home/jpa/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        61: from /home/jpa/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        60: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        59: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
        58: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
        57: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
        56: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
        55: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
        54: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
        53: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:76:in `process'
        52: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:201:in `render'
        51: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `render_docs'
        50: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `each_value'
        49: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `block in render_docs'
        48: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `each'
        47: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:509:in `block (2 levels) in render_docs'
        46: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:523:in `render_regenerated'
        45: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:63:in `run'
        44: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:80:in `render_document'
        43: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:127:in `render_liquid'
        42: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:32:in `render!'
        41: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:60:in `measure_time'
        40: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:33:in `block in render!'
        39: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:53:in `measure_bytes'
        38: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:34:in `block (2 levels) in render!'
        37: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:49:in `measure_counts'
        36: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:35:in `block (3 levels) in render!'
        35: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        34: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        33: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        32: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        31: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        30: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        29: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:122:in `render'
        28: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        27: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:125:in `block in render'
        26: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:32:in `render!'
        25: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:60:in `measure_time'
        24: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:33:in `block in render!'
        23: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:53:in `measure_bytes'
        22: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:34:in `block (2 levels) in render!'
        21: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:49:in `measure_counts'
        20: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:35:in `block (3 levels) in render!'
        19: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        18: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        17: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        16: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        15: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
        14: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        13: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/tags/if.rb:43:in `render'
        12: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        11: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `block in render'
        10: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `each'
         9: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
         8: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
         7: from /home/jpa/gems/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
         6: from /home/jpa/gems/gems/jekyll-responsive-image-1.5.4/lib/jekyll-responsive-image/block.rb:8:in `render'
         5: from /home/jpa/gems/gems/jekyll-responsive-image-1.5.4/lib/jekyll-responsive-image/renderer.rb:24:in `render_responsive_image'
         4: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:379:in `in_source_dir'
         3: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:379:in `reduce'
         2: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:379:in `each'
         1: from /home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:380:in `block in in_source_dir'
/home/jpa/gems/gems/jekyll-4.0.0/lib/jekyll.rb:175:in `sanitized_path': undefined method `start_with?' for nil:NilClass (NoMethodError)
```
